refactor(BUX-612): Remove abstraction over transport layer
bsv-blockchain/spv-wallet-js-client pull request #897
Opened 2024-03-21 09:33 UTC by chris-4chain

Along with this task I've introduced `.prettierrc` file to standarize code formatting - that's in this PR almost every `.ts` file is modified. The prettier configuration is taken from `-web-frontend` repository. 

Main modifications:
- removed `TransportService` interface
- moved out the main `SpvWalletClient` class to a separate file `client.ts`

It is the first task of `-js-client` codebase refactorization.

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet-js-client/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet-js-client/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-03-21 13:24 UTC, pawellewandowski98 approved these changes

2024-03-22 08:16 UTC, wregulski approved these changes

2024-03-22 09:02 UTC, Nazarii-4chain approved these changes

2024-03-22 10:03 UTC, dorzepowski requested changes

2024-03-22 10:36 UTC, chris-4chain commented on src/interface.ts
After the discussion, we decided on `types.ts` because `rollup.js` throws an error when the file name was with `d`.

2024-03-22 10:43 UTC, dorzepowski approved these changes

2024-03-22 10:56 UTC, merged